import React, { createContext, useContext, useState, useEffect } from "react";

export type Language = "en" | "th";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Navigation
    home: "Home",
    events: "Events",
    createEvent: "Create Event",
    manageEvent: "Manage Event",
    viewTickets: "View Your Tickets",

    // Common
    search: "Search",
    filter: "Filter",
    category: "Category",
    date: "Date",
    location: "Location",
    price: "Price",
    free: "Free",
    loading: "Loading...",
    error: "Error",
    success: "Success",
    cancel: "Cancel",
    save: "Save",
    delete: "Delete",
    deleteFailed: "Delete Failed",
    deleteError: "Error occurred while deleting event",
    edit: "Edit",
    view: "View",
    back: "Back",
    next: "Next",
    previous: "Previous",
    submit: "Submit",
    close: "Close",
    clear: "Clear",
    all: "All",

    // Homepage
    heroTitle: "Discover Amazing Events",
    heroSubtitle: "Find and join the most exciting hackathons, conferences, and workshops",
    featuredEvents: "Featured Events",
    categories: "Categories",
    eventsFound: "events found",
    noEventsFound: "No events found",
    viewAllEvents: "View All Events",

    // Event categories
    technology: "Technology",
    music: "Music",
    workshop: "Workshop",
    conference: "Conference",
    entertainment: "Entertainment",
    sports: "Sports & Fitness",
    cultural: "Cultural Event",
    networking: "Networking",
    other: "Other",

    // Event details
    eventDetails: "Event Details",
    register: "Register",
    share: "Share",
    eventId: "Event ID",
    organizer: "Organizer",
    capacity: "Capacity",
    registered: "Registered",
    available: "Available",
    attendees: "attendees",
    seatsAvailable: "seats available",
    onlineEvent: "Online Event",
    virtualEvent: "Virtual Event",
    onsiteEvent: "Onsite Event",
    hybridEvent: "Hybrid Event",

    // Event creation
    createEventTitle: "Create Event",
    createEventSubtitle: "Create your event in a few easy steps",
    organizerInfo: "Organizer Information",
    basicInfo: "Basic Information",
    schedule: "Schedule",
    pricingCapacity: "Pricing & Capacity",
    eventTitle: "Event Title",
    description: "Description",
    eventType: "Event Type",
    status: "Status",
    active: "Active",
    inactive: "Inactive",
    featured: "Featured",
    startDate: "Start Date",
    endDate: "End Date",
    startTime: "Start Time",
    endTime: "End Time",
    timezone: "Timezone",
    venue: "Venue",
    address: "Address",
    fullAddress: "Full Address",
    onlineLink: "Online Link",
    maxCapacity: "Maximum Capacity",
    currency: "Currency",
    ticketTypes: "Ticket Types",
    addTicketType: "Add Ticket Type",
    ticketName: "Ticket Name",
    ticketPrice: "Price",
    ticketDescription: "Description",
    bannerImage: "Banner Image URL",
    thumbnailImage: "Thumbnail Image URL",
    tags: "Tags",
    addTag: "Add Tag",
    requirements: "Requirements",
    addRequirement: "Add Requirement",
    images: "Images",
    gallery: "Gallery",

    // Event management
    manageEventTitle: "Manage Your Event",
    managingEvent: "You are managing",
    requestAccess: "Request Access",
    enterEventId: "Enter Event ID",
    enterEmail: "Enter Email",
    requestOTP: "Request OTP",
    enterOTP: "Enter OTP",
    verifyOTP: "Verify OTP",
    managementActions: "Management Actions",
    deleteEvent: "Delete Event",
    editEvent: "Edit Event Details",
    confirmDelete: "Are you sure you want to delete this event? This action cannot be undone.",
    eventCreated: "Event Created Successfully!",
    eventCreatedDesc: "Your event has been created and the event ID has been sent to",
    manageEventInstructions: "To manage your event",
    goToManageEvent: "Go to the Event Management page",
    enterEventIdEmail: "Enter your Event ID and email address",
    checkEmailOTP: "Check your email for the OTP",
    otpRequested: "OTP Requested",
    otpSentTo: "OTP sent to",
    otpRequestFailed: "OTP Request Failed",
    otpRequestFailedDesc: "Could not generate OTP. Please check your event ID and email.",
    otpRequestError: "Error occurred while requesting OTP",
    verificationSuccess: "Verification Successful",
    manageEventAccess: "You can now manage your event",
    verificationFailed: "Verification failed. Please try again.",
    usernameRequired: "Username Required",
    enterUsernameEmail: "Please enter username or email to search for tickets.",
    noTicketsFound: "No Tickets Found",
    noTicketsForUser: "No tickets found for username",
    checkUsernameRetry: "Please check your username and try again",
    ticketsFound: "Tickets Found",
    foundTicketsFor: "Found tickets for",
    searchError: "Search Error",
    failedToFetchTickets: "Failed to fetch tickets from server. Please try again.",
    failedToLoadEvent: "Failed to load event details.",
    fillRequiredFields: "Please fill in all required fields.",
    registrationSubmitted: "Your registration has been submitted successfully.",
    registrationFailed: "Failed to submit registration. Please try again.",
    platformStats: "Discover insights about our event platform and explore various categories",
    totalEvents: "Total Events",
    categoryDistribution: "Category Distribution",
    categoryDistributionDesc: "Distribution of events by category",
    exploreCategories: "Explore events by category",
    eventsLabel: "events",
    featuredEventsDesc: "Discover our curated selection of interesting events",
    eventsPageDesc: "Discover events that interest you around you",
    bangkok: "Bangkok",
    phuket: "Phuket",
    chiangMai: "Chiang Mai",
    pattaya: "Pattaya",
    createAnotherEvent: "Create Another Event",
    organizerName: "Organizer Name",
    enterOrganizerName: "Enter organizer name",
    organizerEmail: "Organizer Email",
    emailForEventId: "This email will receive your event ID for management",
    phoneNumber: "Phone Number",
    secureEventManagement: "Secure Event Management",
    secureEventManagementDesc: "After creating your event, you'll receive an Event ID at this email address. When you want to manage your event, you'll need to:",
    backToEvents: "Back to Events",
    incompleteData: "Incomplete Data",
    yourEventId: "Your Event ID",
    saveEventId: "Save this ID for event management",
    eventUpdated: "Event Updated Successfully",
    eventUpdatedDesc: "Your event has been updated successfully",
    eventDeleted: "Event Deleted Successfully",
    eventDeletedDesc: "Your event has been deleted successfully",
    pageNotFound: "Oops! Page not found",
    goHome: "Go back to home",

    // Event registration
    registrationTitle: "Event Registration",
    personalInfo: "Personal Information",
    fullName: "Full Name",
    email: "Email",
    phone: "Phone Number",
    company: "Company/Organization",
    ticketSelection: "Ticket Selection",
    selectTicket: "Select Ticket Type",
    quantity: "Quantity",
    additionalInfo: "Additional Information",
    dietaryReq: "Dietary Requirements",
    notes: "Additional Notes",
    orderSummary: "Order Summary",
    total: "Total",
    completeRegistration: "Complete Registration",
    registrationSuccess: "Registration Successful!",
    backToEvent: "Back to Event",
    registrationDetails: "Registration Details",
    ticketType: "Ticket Type",
    pricePerTicket: "Price per Ticket",
    totalAmount: "Total Amount",
    selectTicketType: "Select Ticket Type",
    enterFullName: "Enter your full name",
    enterEmail: "Enter your email address",
    enterPhone: "Enter your phone number",
    enterCompany: "Enter your company",
    dietaryPlaceholder: "Any dietary restrictions or preferences",
    notesPlaceholder: "Any additional information or special requests",
    submitting: "Submitting...",
    completeRegistrationBtn: "Complete Registration",
    selectTicketFirst: "Please select a ticket type to view pricing",
    eventNotFound: "Event Not Found",

    // View tickets
    viewTicketsTitle: "View Your Tickets",
    enterUsername: "Enter username or email",
    searchTickets: "Search Tickets",
    yourTickets: "Your Tickets",
    ticketDetails: "Ticket Details",
    purchaseDate: "Purchase Date",
    showQR: "Show QR Code",

    // Error messages
    requiredField: "This field is required",
    invalidEmail: "Please enter a valid email",
    eventNotFoundDesc: "No event found with this ID",
    failedToLoad: "Failed to load data",
    failedToCreate: "Failed to create event",
    failedToUpdate: "Failed to update event",
    failedToDelete: "Failed to delete event",
    invalidOTP: "Invalid OTP",
    otpExpired: "OTP has expired",

    // Theme toggle
    lightMode: "Light Mode",
    darkMode: "Dark Mode",

    // Dashboard
    upcomingEvents: "Upcoming Events",
    registeredUsers: "Registered Users",
    totalTickets: "Total Tickets",
    eventTrends: "Event Trends",

    // Buttons and actions
    viewDetails: "View Details",
    registerNow: "Register Now",
    buyTickets: "Buy Tickets",
    learnMore: "Learn More",
    contactUs: "Contact Us",
    followUs: "Follow Us",

    // Footer
    aboutUs: "About Us",
    contact: "Contact",
    privacy: "Privacy Policy",
    terms: "Terms of Service",
    copyright: "© 2024 EventHub. All rights reserved.",

    // Form placeholders
    enterTitle: "Enter event title",
    enterDescription: "Describe your event",
    selectCategory: "Select a category",
    enterVenue: "Enter venue name",
    enterAddress: "Enter address",
    enterLink: "Enter online link",
    enterCapacity: "Enter maximum capacity",
    enterTag: "Add tag",
    enterRequirement: "Add requirement",

    // Status messages
    loadingEvents: "Loading events...",
    searching: "Searching...",
    processing: "Processing...",
    sending: "Sending...",
    sentTo: "Sent to",
    step: "Step",
    of: "of",
    completed: "completed",
    at: "at",
    distance: "distance",
    creating: "Creating...",
  },
  th: {
    // Navigation
    home: "หน้าแรก",
    events: "อีเวนต์",
    createEvent: "สร้างอีเวนต์",
    manageEvent: "จัดการอีเวนต์",
    viewTickets: "ดูตั๋วของคุณ",

    // Common
    search: "ค้นหา",
    filter: "กรอง",
    category: "หมวดหมู่",
    date: "วันที่",
    price: "ราคา",
    free: "ฟรี",
    loading: "กำลังโหลด...",
    error: "ข้อผิดพลาด",
    success: "สำเร็จ",
    save: "บันทึก",
    delete: "ลบ",
    deleteFailed: "ลบไม่สำเร็จ",
    deleteError: "เกิดข้อผิดพลาดขณะลบกิจกรรม",
    edit: "แก้ไข",
    view: "ดู",
    back: "กลับ",
    next: "ถัดไป",
    previous: "ก่อนหน้า",
    submit: "ส่ง",
    close: "ปิด",
    clear: "ล้าง",
    all: "ทั้งหมด",

    // Homepage
    heroTitle: "ค้นพบอีเวนต์ที่น่าสนใจ",
    heroSubtitle: "ค้นหาและเข้าร่วมแฮคคาธอน การประชุม และเวิร์คช็อปที่น่าตื่นเต้นที่สุด",
    featuredEvents: "อีเวนต์แนะนำ",
    eventsFound: "พบอีเวนต์",
    noEventsFound: "ไม่พบอีเวนต์",
    viewAllEvents: "ดูกิจกรรมทั้งหมด",

    // Event categories
    technology: "เทคโนโลยี",
    music: "ดนตรี",
    workshop: "เวิร์คช็อป",
    conference: "การประชุม",
    entertainment: "บันเทิง",
    sports: "กีฬาและฟิตเนส",
    cultural: "งานวัฒนธรรม",
    networking: "การสร้างเครือข่าย",
    other: "อื่นๆ",

    // Event details
    eventDetails: "รายละเอียดอีเวนต์",
    register: "ลงทะเบียน",
    share: "แชร์",
    eventId: "รหัสอีเวนต์",
    organizer: "ผู้จัดงาน",
    capacity: "ความจุ",
    registered: "ลงทะเบียนแล้ว",
    available: "ว่าง",
    attendees: "ผู้เข้าร่วม",
    seatsAvailable: "ที่นั่งว่าง",
    onlineEvent: "อีเวนต์ออนไลน์",
    virtualEvent: "อีเวนต์เสมือนจริง",
    onsiteEvent: "อีเวนต์ในสถานที่",
    hybridEvent: "อีเวนต์ผสม",

    // Event creation
    createEventTitle: "สร้างอีเวนต์",
    createEventSubtitle: "สร้างอีเวนต์ของคุณในไม่กี่ขั้นตอนง่ายๆ",
    organizerInfo: "ข้อมูลผู้จัดงาน",
    basicInfo: "ข้อมูลพื้นฐาน",
    schedule: "กำหนดการ",
    pricingCapacity: "ราคาและความจุ",
    eventTitle: "ชื่ออีเวนต์",
    description: "คำอธิบาย",
    eventType: "ประเภทอีเวนต์",
    status: "สถานะ",
    active: "ใช้งาน",
    inactive: "ไม่ใช้งาน",
    featured: "แนะนำ",
    startDate: "วันที่เริ่ม",
    endDate: "วันที่สิ้นสุด",
    startTime: "เวลาเริ่ม",
    endTime: "เวลาสิ้นสุด",
    timezone: "เขตเวลา",
    venue: "สถานที่จัดงาน",
    address: "ที่อยู่",
    fullAddress: "ที่อยู่เต็ม",
    onlineLink: "ลิงก์ออนไลน์",
    maxCapacity: "ความจุสูงสุด",
    currency: "สกุลเงิน",
    ticketTypes: "ประเภทตั๋ว",
    addTicketType: "เพิ่มประเภทตั๋ว",
    ticketName: "ชื่อตั๋ว",
    ticketPrice: "ราคา",
    ticketDescription: "คำอธิบาย",
    bannerImage: "URL รูปภาพแบนเนอร์",
    thumbnailImage: "URL รูปภาพย่อ",
    tags: "แท็ก",
    addTag: "เพิ่มแท็ก",
    requirements: "ข้อกำหนด",
    addRequirement: "เพิ่มข้อกำหนด",
    images: "รูปภาพ",
    gallery: "แกลเลอรี่",

    // Event management
    manageEventTitle: "จัดการอีเวนต์ของคุณ",
    managingEvent: "คุณกำลังจัดการ",
    requestAccess: "ขอสิทธิ์การเข้าถึง",
    enterEventId: "ป้อนรหัสอีเวนต์",
    enterEmail: "ป้อนอีเมล",
    requestOTP: "ขอ OTP",
    enterOTP: "ป้อน OTP",
    verifyOTP: "ยืนยัน OTP",
    managementActions: "การดำเนินการจัดการ",
    deleteEvent: "ลบอีเวนต์",
    editEvent: "แก้ไขรายละเอียดอีเวนต์",
    confirmDelete: "คุณแน่ใจหรือไม่ว่าต้องการลบอีเวนต์นี้? การดำเนินการนี้ไม่สามารถยกเลิกได้.",
    eventCreated: "สร้างอีเวนต์สำเร็จ!",
    eventCreatedDesc: "อีเวนต์ของคุณถูกสร้างแล้ว และรหัสอีเวนต์ถูกส่งไปยัง",
    manageEventInstructions: "เพื่อจัดการอีเวนต์ของคุณ",
    goToManageEvent: "ไปที่หน้า การจัดการอีเวนต์",
    enterEventIdEmail: "ป้อนรหัสกิจกรรมและที่อยู่อีเมลของคุณ",
    checkEmailOTP: "ตรวจสอบอีเมลของคุณสำหรับ OTP",
    otpRequested: "ขอ OTP แล้ว",
    otpSentTo: "OTP ถูกส่งไปยัง",
    otpRequestFailed: "ขอ OTP ไม่สำเร็จ",
    otpRequestFailedDesc: "ไม่สามารถสร้าง OTP ได้. กรุณาตรวจสอบรหัสกิจกรรมและอีเมลของคุณ.",
    otpRequestError: "เกิดข้อผิดพลาดขณะขอ OTP",
    verificationSuccess: "การยืนยันสำเร็จ",
    manageEventAccess: "ตอนนี้คุณสามารถจัดการกิจกรรมของคุณได้",
    verificationFailed: "การยืนยันล้มเหลว. กรุณาลองใหม่อีกครั้ง.",
    usernameRequired: "ต้องมีชื่อผู้ใช้",
    enterUsernameEmail: "กรุณาป้อนชื่อผู้ใช้หรืออีเมลเพื่อค้นหาตั๋ว.",
    noTicketsFound: "ไม่พบตั๋ว",
    noTicketsForUser: "ไม่พบตั๋วสำหรับชื่อผู้ใช้",
    checkUsernameRetry: "กรุณาตรวจสอบชื่อผู้ใช้และลองใหม่อีกครั้ง",
    ticketsFound: "พบตั๋วแล้ว",
    foundTicketsFor: "พบตั๋วสำหรับ",
    searchError: "ข้อผิดพลาดในการค้นหา",
    failedToFetchTickets: "ไม่สามารถดึงตั๋วจากเซิร์ฟเวอร์ได้. กรุณาลองใหม่อีกครั้ง.",
    failedToLoadEvent: "ไม่สามารถโหลดรายละเอียดกิจกรรมได้.",
    fillRequiredFields: "กรุณากรอกข้อมูลในช่องที่จำเป็นทั้งหมด.",
    registrationSubmitted: "การลงทะเบียนของคุณถูกส่งเรียบร้อยแล้ว.",
    registrationFailed: "ไม่สามารถส่งการลงทะเบียนได้. กรุณาลองใหม่อีกครั้ง.",
    platformStats: "รับข้อมูลเชิงลึกเกี่ยวกับแพลตฟอร์มกิจกรรมของเราและสำรวจหมวดหมู่ต่างๆ",
    totalEvents: "กิจกรรมทั้งหมด",
    categories: "หมวดหมู่",
    categoryDistribution: "การกระจายหมวดหมู่",
    categoryDistributionDesc: "การกระจายกิจกรรมตามหมวดหมู่",
    exploreCategories: "สำรวจกิจกรรมตามหมวดหมู่",
    eventsLabel: "events",
    featuredEventsDesc: "ค้นพบการคัดเลือกกิจกรรมที่น่าสนใจของเรา",
    eventsPageDesc: "ค้นพบกิจกรรมที่น่าสนใจที่เกิดขึ้นรอบตัวคุณ",
    bangkok: "กรุงเทพฯ",
    phuket: "ภูเก็ต",
    chiangMai: "เชียงใหม่",
    pattaya: "พัทยา",
    createAnotherEvent: "สร้างกิจกรรมอีกครั้ง",
    organizerName: "ชื่อผู้จัดงาน",
    enterOrganizerName: "ป้อนชื่อผู้จัดงาน",
    organizerEmail: "อีเมลผู้จัดงาน",
    emailForEventId: "อีเมลนี้จะได้รับรหัสกิจกรรมสำหรับการจัดการ",
    phoneNumber: "หมายเลขโทรศัพท์",
    secureEventManagement: "การจัดการกิจกรรมที่ปลอดภัย",
    secureEventManagementDesc: "หลังจากสร้างกิจกรรมแล้ว คุณจะได้รับรหัสกิจกรรมที่อีเมลนี้ เมื่อคุณต้องการจัดการกิจกรรม คุณจะต้อง:",
    yourEventId: "รหัสกิจกรรมของคุณ",
    saveEventId: "บันทึกรหัสนี้สำหรับการจัดการกิจกรรม",
    eventUpdated: "อัปเดตกิจกรรมสำเร็จ",
    eventUpdatedDesc: "กิจกรรมของคุณถูกอัปเดตเรียบร้อยแล้ว",
    eventDeleted: "ลบกิจกรรมสำเร็จ",
    eventDeletedDesc: "กิจกรรมของคุณถูกลบเรียบร้อยแล้ว",

    // Event registration
    registrationTitle: "การลงทะเบียนอีเวนต์",
    personalInfo: "ข้อมูลส่วนตัว",
    fullName: "ชื่อเต็ม",
    email: "อีเมล",
    phone: "หมายเลขโทรศัพท์",
    company: "บริษัท/องค์กร",
    ticketSelection: "การเลือกตั๋ว",
    selectTicket: "เลือกประเภทตั๋ว",
    quantity: "จำนวน",
    additionalInfo: "ข้อมูลเพิ่มเติม",
    dietaryReq: "ข้อกำหนดด้านอาหาร",
    notes: "หมายเหตุเพิ่มเติม",
    orderSummary: "สรุปคำสั่งซื้อ",
    total: "รวม",
    completeRegistration: "เสร็จสิ้นการลงทะเบียน",
    registrationSuccess: "การลงทะเบียนสำเร็จ!",
    backToEvent: "กลับไปยังกิจกรรม",
    registrationDetails: "รายละเอียดการลงทะเบียน",
    ticketType: "ประเภทตั๋ว",
    pricePerTicket: "ราคาต่อตั๋ว",
    totalAmount: "จำนวนเงินรวม",
    selectTicketType: "เลือกประเภทตั๋ว",
    enterFullName: "ป้อนชื่อเต็มของคุณ",
    enterPhone: "ป้อนหมายเลขโทรศัพท์ของคุณ",
    enterCompany: "ป้อนชื่อบริษัทของคุณ",
    dietaryPlaceholder: "ข้อจำกัดด้านอาหารหรือความชอบใดๆ",
    notesPlaceholder: "ข้อมูลเพิ่มเติมหรือคำขอพิเศษใดๆ",
    cancel: "ยกเลิก",
    submitting: "กำลังส่ง...",
    completeRegistrationBtn: "เสร็จสิ้นการลงทะเบียน",
    selectTicketFirst: "กรุณาเลือกประเภทตั๋วเพื่อดูราคา",
    eventNotFound: "ไม่พบกิจกรรม",
    backToEvents: "กลับไปยังกิจกรรม",

    // View tickets
    viewTicketsTitle: "ดูตั๋วของคุณ",
    enterUsername: "ป้อนชื่อผู้ใช้หรืออีเมล",
    searchTickets: "ค้นหาตั๋ว",
    yourTickets: "ตั๋วของคุณ",
    ticketDetails: "รายละเอียดตั๋ว",
    purchaseDate: "วันที่ซื้อ",
    showQR: "แสดงรหัส QR",

    // Error messages
    requiredField: "ฟิลด์นี้จำเป็น",
    invalidEmail: "กรุณาป้อนอีเมลที่ถูกต้อง",
    eventNotFoundDesc: "ไม่พบอีเวนต์ที่มีรหัสนี้",
    failedToLoad: "ไม่สามารถโหลดข้อมูลได้",
    failedToCreate: "ไม่สามารถสร้างอีเวนต์ได้",
    failedToUpdate: "ไม่สามารถอัปเดตอีเวนต์ได้",
    failedToDelete: "ไม่สามารถลบอีเวนต์ได้",
    invalidOTP: "OTP ไม่ถูกต้อง",
    otpExpired: "OTP หมดอายุ",

    // Theme toggle
    lightMode: "โหมดสว่าง",
    darkMode: "โหมดมืด",

    // Dashboard
    upcomingEvents: "อีเวนต์ที่กำลังจะมาถึง",
    registeredUsers: "ผู้ใช้ที่ลงทะเบียน",
    totalTickets: "ตั๋วทั้งหมด",
    eventTrends: "แนวโน้มอีเวนต์",

    // Buttons and actions
    viewDetails: "ดูรายละเอียด",
    registerNow: "ลงทะเบียนเลย",
    buyTickets: "ซื้อตั๋ว",
    learnMore: "เรียนรู้เพิ่มเติม",
    contactUs: "ติดต่อเรา",
    followUs: "ติดตามเรา",

    // Footer
    aboutUs: "เกี่ยวกับเรา",
    contact: "ติดต่อ",
    privacy: "นโยบายความเป็นส่วนตัว",
    terms: "เงื่อนไขการให้บริการ",
    copyright: "© 2024 EventHub. สงวนลิขสิทธิ์.",

    // Form placeholders
    enterTitle: "ป้อนชื่ออีเวนต์",
    enterDescription: "อธิบายอีเวนต์ของคุณ",
    selectCategory: "เลือกหมวดหมู่",
    enterVenue: "ป้อนชื่อสถานที่",
    enterAddress: "ป้อนที่อยู่",
    enterLink: "ป้อนลิงก์ออนไลน์",
    enterCapacity: "ป้อนความจุสูงสุด",
    enterTag: "เพิ่มแท็ก",
    enterRequirement: "เพิ่มข้อกำหนด",

    // Status messages
    loadingEvents: "กำลังโหลดอีเวนต์...",
    searching: "กำลังค้นหา...",
    processing: "กำลังดำเนินการ...",
    sending: "กำลังส่ง...",
    sentTo: "ถูกส่งไปยัง",
    step: "ขั้นตอน",
    of: "จาก",
    completed: "เสร็จสิ้น",
    at: "เวลา",
    distance: "ระยะทาง",
    creating: "กำลังสร้าง...",
    incompleteData: "ข้อมูลไม่ครบ",
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  useEffect(() => {
    const savedLanguage = localStorage.getItem("language") as Language;
    if (savedLanguage && (savedLanguage === "en" || savedLanguage === "th")) {
      setLanguage(savedLanguage);
    }
  }, []);

  const setLanguageAndSave = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("language", lang);
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations[typeof language]] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: setLanguageAndSave, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}